### scilit-learn中的Scaler

In [2]:
import numpy as np
from sklearn import datasets

In [3]:
iris = datasets.load_iris() # 加载鸢尾花的数据

In [4]:
X = iris.data # 记载测试数据
y = iris.target # 记载标签

In [5]:
X[:10,:] # 查看前10行的内容

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [8]:
from sklearn.model_selection import train_test_split 

In [10]:
X_Train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,random_state=666) # 分成训练数据集跟测试数据集

### scilit-learn中的StandardScaler  均值方差归一化

In [11]:
from sklearn.preprocessing import StandardScaler # 数据预处理包中import

In [14]:
standardScaler = StandardScaler()
standardScaler.fit(X_Train) # 将返回自身关键信息

StandardScaler(copy=True, with_mean=True, with_std=True)

In [15]:
standardScaler.mean_ # 四个特征对应的均值

array([5.825     , 3.08839286, 3.68660714, 1.16339286])

In [17]:
standardScaler.scale_ # 描述数据的分布范围,即四个特征对应的方差

array([0.80239597, 0.44676327, 1.75715352, 0.75663677])

In [18]:
standardScaler.transform(X_Train) # 虽数据进行归一化处理

array([[-0.77891718,  2.26430241, -1.24440302, -1.40542054],
       [ 0.46735031, -1.98850918,  0.4629037 ,  0.44487283],
       [ 1.83824454, -0.42168386,  1.48728772,  0.84136427],
       [ 0.7166038 ,  0.24981271,  0.91818549,  1.50218333],
       [ 0.21809681,  0.69747709,  0.4629037 ,  0.57703664],
       [-0.77891718, -0.86934823,  0.12144235,  0.31270902],
       [-0.52966368,  1.36897365, -1.24440302, -1.27325673],
       [-0.65429043,  1.36897365, -1.24440302, -1.27325673],
       [-1.02817067,  0.92130928, -1.18749279, -0.74460148],
       [-1.77593116, -0.42168386, -1.30131324, -1.27325673],
       [-0.03115669, -0.86934823,  0.12144235,  0.0483814 ],
       [-0.77891718,  0.69747709, -1.30131324, -1.27325673],
       [-1.52667767,  0.69747709, -1.30131324, -1.14109291],
       [ 0.84123055,  0.24981271,  0.80436504,  1.10569189],
       [-0.15578344, -0.42168386,  0.29217302,  0.18054521],
       [ 0.9658573 , -0.19785167,  0.40599347,  0.31270902],
       [ 0.21809681, -0.

In [19]:
X_Train = standardScaler.transform(X_Train) # 改变一下x_train

In [20]:
X_Train

array([[-0.77891718,  2.26430241, -1.24440302, -1.40542054],
       [ 0.46735031, -1.98850918,  0.4629037 ,  0.44487283],
       [ 1.83824454, -0.42168386,  1.48728772,  0.84136427],
       [ 0.7166038 ,  0.24981271,  0.91818549,  1.50218333],
       [ 0.21809681,  0.69747709,  0.4629037 ,  0.57703664],
       [-0.77891718, -0.86934823,  0.12144235,  0.31270902],
       [-0.52966368,  1.36897365, -1.24440302, -1.27325673],
       [-0.65429043,  1.36897365, -1.24440302, -1.27325673],
       [-1.02817067,  0.92130928, -1.18749279, -0.74460148],
       [-1.77593116, -0.42168386, -1.30131324, -1.27325673],
       [-0.03115669, -0.86934823,  0.12144235,  0.0483814 ],
       [-0.77891718,  0.69747709, -1.30131324, -1.27325673],
       [-1.52667767,  0.69747709, -1.30131324, -1.14109291],
       [ 0.84123055,  0.24981271,  0.80436504,  1.10569189],
       [-0.15578344, -0.42168386,  0.29217302,  0.18054521],
       [ 0.9658573 , -0.19785167,  0.40599347,  0.31270902],
       [ 0.21809681, -0.

In [21]:
standardScaler.transform(X_test)

array([[-0.28041018, -0.19785167,  0.4629037 ,  0.44487283],
       [-0.03115669, -0.64551604,  0.80436504,  1.63434714],
       [-1.02817067, -1.76467699, -0.22001899, -0.21594623],
       [-0.03115669, -0.86934823,  0.80436504,  0.97352808],
       [-1.52667767,  0.02598052, -1.24440302, -1.27325673],
       [-0.40503693, -1.31701261,  0.17835258,  0.18054521],
       [-0.15578344, -0.64551604,  0.4629037 ,  0.18054521],
       [ 0.84123055, -0.19785167,  0.86127526,  1.10569189],
       [ 0.59197705, -1.76467699,  0.40599347,  0.18054521],
       [-0.40503693, -1.09318042,  0.40599347,  0.0483814 ],
       [ 1.09048405,  0.02598052,  0.40599347,  0.31270902],
       [-1.65130441, -1.76467699, -1.35822347, -1.14109291],
       [-1.27742417,  0.02598052, -1.18749279, -1.27325673],
       [-0.52966368,  0.69747709, -1.24440302, -1.0089291 ],
       [ 1.71361779,  1.14514147,  1.37346728,  1.76651095],
       [-0.03115669, -0.86934823,  0.2352628 , -0.21594623],
       [-1.52667767,  1.

In [22]:
X_test_standerd = standardScaler.transform(X_test) # 保存归一化后的数据

In [23]:
X_test_standerd

array([[-0.28041018, -0.19785167,  0.4629037 ,  0.44487283],
       [-0.03115669, -0.64551604,  0.80436504,  1.63434714],
       [-1.02817067, -1.76467699, -0.22001899, -0.21594623],
       [-0.03115669, -0.86934823,  0.80436504,  0.97352808],
       [-1.52667767,  0.02598052, -1.24440302, -1.27325673],
       [-0.40503693, -1.31701261,  0.17835258,  0.18054521],
       [-0.15578344, -0.64551604,  0.4629037 ,  0.18054521],
       [ 0.84123055, -0.19785167,  0.86127526,  1.10569189],
       [ 0.59197705, -1.76467699,  0.40599347,  0.18054521],
       [-0.40503693, -1.09318042,  0.40599347,  0.0483814 ],
       [ 1.09048405,  0.02598052,  0.40599347,  0.31270902],
       [-1.65130441, -1.76467699, -1.35822347, -1.14109291],
       [-1.27742417,  0.02598052, -1.18749279, -1.27325673],
       [-0.52966368,  0.69747709, -1.24440302, -1.0089291 ],
       [ 1.71361779,  1.14514147,  1.37346728,  1.76651095],
       [-0.03115669, -0.86934823,  0.2352628 , -0.21594623],
       [-1.52667767,  1.

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn_clf = KNeighborsClassifier(n_neighbors=3) # 创建分类器

In [26]:
knn_clf.fit(X_Train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [43]:
knn_clf.score(X_test_standerd,y_test) # 此时分类器的准确度

0.9736842105263158

In [44]:
knn_clf.score(X_test,y_test) # 取消数据归一化后分类器的准确度

0.34210526315789475